# Generated by Django 4.2.7 on 2026-02-03 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('organization', models.CharField(max_length=200, verbose_name='Organización')),
                ('date', models.CharField(max_length=50, verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución/Plataforma')),
                ('date', models.CharField(max_length=50, verbose_name='Fecha')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Duración')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('certificate_url', models.URLField(blank=True, verbose_name='URL del certificado')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('degree', models.CharField(max_length=200, verbose_name='Título/Grado')),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True, verbose_name='Campo de estudio')),
                ('start_date', models.CharField(max_length=50, verbose_name='Fecha de inicio')),
                ('end_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_current', models.BooleanField(default=False, verbose_name='En curso')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ['-order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_date', models.CharField(max_length=50, verbose_name='Fecha de inicio')),
                ('end_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='Tecnologías usadas')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Eivy René Romero Mendoza', max_length=200)),
                ('title', models.CharField(default='Full Stack Developer', max_length=200)),
                ('email', models.EmailField(default='eivyromero.26@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+593 98 721 3633', max_length=50)),
                ('location', models.CharField(default='Guayaquil, Ecuador', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technologies', models.CharField(blank=True, max_length=200, verbose_name='Tecnologías')),
                ('url', models.URLField(blank=True, verbose_name='URL del proyecto')),
                ('github_url', models.URLField(blank=True, verbose_name='URL de GitHub')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('start_date', models.CharField(blank=True, max_length=50, verbose_name='Fecha de inicio')),
                ('end_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de fin')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='🔧', max_length=10, verbose_name='Icono')),
                ('price_info', models.CharField(blank=True, max_length=200, verbose_name='Información de precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de Datos'), ('tools', 'Herramientas'), ('other', 'Otros')], default='other', max_length=20)),
                ('icon', models.CharField(default='💻', max_length=10)),
                ('level', models.IntegerField(default=50, help_text='Nivel de 0 a 100')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
